# Generated by Django 3.2.7 on 2021-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='free_places',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
